네비게이션바 오류 수정
AI-Funding/AI_Funding_FE pull request #116
Opened 2022-10-08 04:32 UTC by hyeonzii

-커뮤니티 글 읽기, 게시판 화면에서 네비게이션 바 선택이 안되는 오류 수정

2022-10-08 06:46 UTC, chb09876 requested changes

2022-10-08 06:46 UTC, chb09876 commented on src/pages/Communitypage/Component/Board.jsx
>      const [SelectedClass,SelectClass]=useState("공지");
첫글자는 소문자인 카멜케이스로 변경 부탁드립니다..!

2022-10-08 06:46 UTC, chb09876 commented on src/pages/Communitypage/Read.jsx
>    const [Heart,SetHeart]=useState('unclicked');
요기도 마찬가지로 camelCase로 부탁드립니다!

2022-10-08 15:31 UTC, hyeonzii commented on src/pages/Communitypage/Read.jsx
>    const [Heart,SetHeart]=useState('unclicked');
넵~~~

2022-10-08 15:32 UTC, hyeonzii commented on src/pages/Communitypage/Component/Board.jsx
>      const [SelectedClass,SelectClass]=useState("공지");
넵~~

2022-10-09 06:32 UTC, chb09876 commented on src/pages/Communitypage/Component/Board.jsx
>      const [SelectedClass,SelectClass]=useState("공지");
수고하셨습니다!

2022-10-09 06:32 UTC, chb09876 approved these changes

2022-10-09 06:32 UTC, merged