홈화면 sample 제작, 전역 설정, 폴더 구조 추가,
AI-Funding/AI_Funding_FE pull request #22
Opened 2022-01-12 20:47 UTC by chb09876

## 홈화면 sample
이전에 다들 만들어주셨던 컴포넌트들을 조금 수정하고 조합해 home 페이지 샘플을 만들었습니다..!
sample폴더에 해당 코드가 들어있습니다.
.css로 작성하셨던 css는 styled component를 이용해 적용하도록 바꿨고,
class형 컴포넌트도 함수형 컴포넌트로 바꿨씁니다.
또한 몇몇 컴포넌트는 props가 없는 경우 default값을 사용하도록 하였습니다.
그리고 styled-component 재사용을 위해 props로 className을 받아와 적용하도록 수정하였습니다.
본인이 이전에 작성하셨던 코드와 비교해보시고 이해안되는 부분있으면 질문 주세요!
앞으로 작업하실때 sample코드를 참고하시면 될 것 같습니다.

홈화면 sample을 만들기 위해 만드셨던 브랜치들은 별도의 pr없이 삭제해주셔도 됩니다.

## 전역설정

### index.js
GlobalStyle을 추가하였습니다. 해당 컴포넌트는 style/GlobalStyle.jsx에서 관리하는 전역 스타일을 적용해줍니다.
BrowserRouter를 추가하였습니다. react-router-dom의 라우팅 기능을 이용하는데 필요합니다.

### GlobalStyle.jsx
- font 적용
- 모든 태그 box-sizing: border-box 적용
- p 태그 font-size: 15px, color: white 적용
- html, body, #root 태그 width: 100%, height: 100% 적용 -> 배경레이아웃 디바이스 크기에 맞추기 위해서!
- body 태그 font: spoqa.., margin: 0px 적용

### App.js
![image](https://user-images.githubusercontent.com/64854140/149217019-6bfc59e7-3d48-4280-80c7-0e45baa9942f.png)
위 코드처럼 BackgroundLayout컴포넌트 안에 페이지 컴포넌트와 네비게이션 컴포넌트가 나오도록 설정하였습니다.
BackgroundLayout컴포넌트에 대해선 노션 문서를 참고해주시면 감사하겠습니다.

현재 App.js는 sample폴더의 코드를 렌더링하도록 설정되어있습니다. 해당 부분은 개발하시면서 바꿔주시면 감사하겠습니다.

## 폴더 구조 추가
여러 페이지에서 공통적으로 필요한 컴포넌트를 넣는 common폴더를 추가하였습니다.
현재 BackgroundLayout과 네비게이션에 관한 컴포넌트가 들어있습니다.

## 노션 문서 추가
노션에 개발 규칙 문서와 다른 가이드 문서들을 작성하였습니다.  특히 레이아웃에 대한 글은 꼭 확인해주시고 이해 안되는 부분 질문 부탁드립니다.

## 추가된 모듈
현재 네비게이션의 아이콘 관련한 모듈이 추가되었습니다. 따라서 localhost실행 전 npm install명령어로 해당 모듈을 설치하시고 실행해야 정상적으로 렌더링이 될 겁니다.

2022-01-13 08:28 UTC, HoSeong0731 requested changes
동일한 이미지 파일이 2개더라구요! 확인하고 삭제 부탁드립니다.

2022-01-13 08:28 UTC, HoSeong0731 commented on src/sample/pages/home/presentational/C.jsx
> +export default function ComponentC(props) {
cup.png파일 필요없는 거 삭제 부탁드립니다. 중복이네요

2022-01-13 08:46 UTC, chb09876 commented on src/sample/pages/home/presentational/C.jsx
> +export default function ComponentC(props) {
확인 감사드립니다! src/image/cup.png를 삭제하고 src/sample/image/cup.png를 남겨두었습니다.

2022-01-13 08:57 UTC, HoSeong0731 commented on src/sample/pages/home/presentational/C.jsx
> +export default function ComponentC(props) {
그냥 질문이긴 한데 sample 디렉토리 안에 있는 png를 남긴 특별한 이유가 있을까요??

2022-01-13 09:20 UTC, chb09876 commented on src/sample/pages/home/presentational/C.jsx
> +export default function ComponentC(props) {
sample의 코드는 src/sample/image의 cup.png를 가져오도록 되어있습니다. 만약 src/image에서 가져오도록 한다면 추후에 image가 수정되거나 하였을 때 sample코드가 렌더링이 제대로 안될거 같아 sample디렉토리 안에 넣어놓았습니다. 정리하자면 sample디렉토리의 코드는 정말 가이드용이라 앞으로 수정될일이 없을 예정이고, 실제 개발은 sample디렉토리의 바깥에서 일어나기 때문에 sample폴더는 독립적이라고 보시면 됩니다. 따라서 외부 리소스의 변경에 영향을 받지 않게 할려고 sample디렉토리에 png를 남겼습니다. 만약 개발하면서 cup.png가 필요하면 src/image에 복사해서 사용하면 될거 같습니다.

2022-01-14 00:54 UTC, HoSeong0731 commented on src/sample/pages/home/presentational/C.jsx
> +export default function ComponentC(props) {
넵! 확인했습니다 :)

2022-01-16 04:04 UTC, merged

2022-01-16 12:32 UTC, mouse0429 approved these changes